### ISSUE TITLE
vref Value - Irms

### ISSUE THREAD

**Issue by innlight** [coolio986/Marlin_2.0.x_Anycubic_Chiron#6]
Hi, Thanks for your wonderfull work. Now i want to know the vref value of original sepper motors for calculate the Irms values to sets my TMC2209.
Thanks

**Comment by coolio986** [comment]
Anycubic hasn't specifically released the coil voltage for these motors. One could take a multimeter and measure the coil resistance and convert that to coil voltage, which can then be converted to Irms.

Since I don't know, and the tmc drivers manage the Irms by setting the limits in the firmware, it's a bit irrelevant. The parameters defined in the firmware are compatible with the stock motors.
